SRC_CRS = "EPSG:2100"
TARGET_CRS = "EPSG:4326"

MATERIAL_COLORS = {
	'Asbestos Cement': "#FF0000",
	'PVC': "#00FF00",
	'Steel': "#0000FF",
	'HDPE': "#FFFF00",
	'Cast iron': "#00FFFF",
}

LEFT_MENU = [
	{
		"name": "Setting the topology",
		"step": 0,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
 	{
		"name": "Pipe network",
		"step": 0,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
  	{
		"name": "Damages",
		"step": 0,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
   	{
		"name": "Risk assessment (topological metrics)",
		"step": 1,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Betweeness metric",
		"step": 1,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Closeness metric",
		"step": 1,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Bridges metric",
		"step": 1,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Composite metric",
		"step": 1,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Risk assessment (Combined metrics/damages)",
		"step": 2,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Criticality maps per cell size",
		"step": 2,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "LISA results",
		"step": 2,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Risk assessment (Optimal / Selected cell size)",
		"step": 3,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Criticality map for selected cell size",
		"step": 3,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "LCC optimization",
		"step": 4,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Optimized cells",
		"step": 4,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Decision support tool for pipe replacement",
		"step": 5,
		"leaf": False,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Select group of pipes based on criteria",
		"step": 5,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
    {
		"name": "Pipe grouping",
		"step": 5,
		"leaf": True,
		"selected": False,
		"completed": False,
	},
]